# Fixed splash screen issue version of pubspec.yaml
name: eldercareapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

# Dependencies specify other packages your package needs to work.
# To automatically upgrade your package dependencies to the latest versions,
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  fl_chart: ^1.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

# ==============================
# FLUTTER NATIVE SPLASH CONFIG
# ==============================
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/eldercare-logo-black.png
  image_dark: assets/logos/eldercare-logo-black.png
  android: true
  android_gravity: center
  android_12:
    image: assets/logos/eldercare-logo-black.png
    image_dark: assets/logos/eldercare-logo-black.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#272727"
  ios: true
  ios_content_mode: center
  web: false

# ==============================
# FLUTTER CONFIGURATION
# ==============================
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/eldercare-logo-black.png
    - assets/logos/eldercare-logo-white.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here
