class QRCodeService {
  static final QRCodeService _instance = QRCodeService._internal();

  factory QRCodeService() {
    return _instance;
  }

  QRCodeService._internal();

  /// Parse smartwatch pairing ID from QR code
  /// QR code format: WATCH_XXXXXX (generated by smartwatch app)
  /// Example: WATCH_ABC123
  String? parseSmartwatchQRCode(String qrData) {
    try {
      // Check if it's a valid watch pairing ID (WATCH_XXXXXX format)
      if (qrData.startsWith('WATCH_')) {
        return qrData;
      }
      
      // Also support patient_id format for backwards compatibility
      if (qrData.startsWith('patient_id:')) {
        return qrData.substring('patient_id:'.length);
      }
      
      if (qrData.startsWith('patient_')) {
        return qrData;
      }

      return null;
    } catch (e) {
      print('Error parsing QR code: $e');
      return null;
    }
  }

  /// Check if the scanned code is a smartwatch pairing ID (WATCH_XXXXXX format)
  bool isSmartwatchPairingId(String id) {
    return id.startsWith('WATCH_') && id.length == 12; // WATCH_ + 6 characters
  }

  /// Check if the scanned code is a patient ID format
  bool isPatientId(String id) {
    return RegExp(r'^patient_[a-zA-Z0-9]+$').hasMatch(id);
  }

  /// Validate any smartwatch ID format
  bool isValidSmartwatchId(String id) {
    return isSmartwatchPairingId(id) || isPatientId(id);
  }

  /// Generate QR code data string for smartwatch
  /// Returns formatted string that can be converted to QR code
  String generateSmartwatchQRData(String patientId) {
    return 'patient_id:$patientId';
  }
}
